import React from 'react';
import Link from 'next/link';
import { Bot, Mic, Zap, ShieldCheck } from 'lucide-react';
import Navbar from '@/components/shared/Navbar';
import Footer from '@/components/shared/Footer';
import { Button } from '@/components/ui/Button';

const LandingPage = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      
      <main className="flex-1">
        {/* Hero Section */}
        <section className="container mx-auto px-6 py-24 text-center">
          <h1 className="text-5xl md:text-7xl font-bold tracking-tight">
            Never Feel Stuck in an <span className="text-indigo-400">Interview</span> Again
          </h1>
          <p className="mt-6 max-w-2xl mx-auto text-lg text-gray-300">
            Get real-time, AI-powered suggestions for any interview question. Speak confidently and land your dream job.
          </p>
          <div className="mt-8">
            <Link href="/signup">
              <Button size="lg" className="transform hover:scale-105 transition-transform duration-300">
                Get Started for Free
              </Button>
            </Link>
          </div>
        </section>

        {/* Features Section */}
        <section className="bg-gray-800/50 py-20">
          <div className="container mx-auto px-6">
            <div className="text-center mb-12">
              <h2 className="text-4xl font-bold">How It Helps You Succeed</h2>
              <p className="mt-2 text-gray-400">Everything you need to perform at your best.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {/* Feature 1 */}
              <div className="text-center p-8 bg-gray-900 rounded-2xl border border-gray-700">
                <div className="flex justify-center items-center mb-4 bg-indigo-500/10 rounded-full h-16 w-16 mx-auto">
                  <Mic size={32} className="text-indigo-400" />
                </div>
                <h3 className="text-xl font-semibold">Real-Time Assistance</h3>
                <p className="mt-2 text-gray-400">Our AI listens as you do and provides instant, discreet suggestions on-screen.</p>
              </div>
              {/* Feature 2 */}
              <div className="text-center p-8 bg-gray-900 rounded-2xl border border-gray-700">
                <div className="flex justify-center items-center mb-4 bg-indigo-500/10 rounded-full h-16 w-16 mx-auto">
                  <Bot size={32} className="text-indigo-400" />
                </div>
                <h3 className="text-xl font-semibold">Powered by Gemini</h3>
                <p className="mt-2 text-gray-400">Get intelligent, context-aware answers generated by Google's powerful AI models.</p>
              </div>
              {/* Feature 3 */}
              <div className="text-center p-8 bg-gray-900 rounded-2xl border border-gray-700">
                <div className="flex justify-center items-center mb-4 bg-indigo-500/10 rounded-full h-16 w-16 mx-auto">
                  <Zap size={32} className="text-indigo-400" />
                </div>
                <h3 className="text-xl font-semibold">Supports All Interviews</h3>
                <p className="mt-2 text-gray-400">Whether it's a technical coding round or a behavioral discussion, we've got you covered.</p>
              </div>
            </div>
          </div>
        </section>
        
        {/* Final CTA Section */}
        <section className="container mx-auto px-6 py-24 text-center">
            <h2 className="text-4xl font-bold">Ready to Ace Your Next Interview?</h2>
            <p className="mt-4 text-lg text-gray-300">Stop worrying and start preparing with your personal AI assistant.</p>
            <div className="mt-8">
              <Link href="/signup">
                <Button size="lg" className="bg-white text-gray-900 hover:bg-gray-200">
                  Sign Up Now
                </Button>
              </Link>
            </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
};

export default LandingPage;
